import { mkdir } from "node:fs/promises";

const methods = ["system.bootstrap", "system.quit", "window.close", "window.getModel", "titles.list", "titles.refresh", "titles.launch", "emulation.stop"] as const;
await mkdir(new URL("../src/generated/", import.meta.url), { recursive: true });
await Bun.write(new URL("../src/generated/methods.ts", import.meta.url), `// Generated by scripts/generate-contracts.ts\nexport const rpcMethods = ${JSON.stringify(methods)} as const;\nexport type RpcMethod = typeof rpcMethods[number];\n`);
