import { mkdir } from "node:fs/promises";

type ContractManifest = {
  windowRoles: string[];
  implementedWindowRoles: string[];
  methods: Array<{ name: string; params: string; result: string }>;
};

const manifest = await Bun.file(new URL("../contracts/rpc.json", import.meta.url)).json() as ContractManifest;
if (!Array.isArray(manifest.methods) || manifest.methods.length === 0) throw new Error("RPC contract must define methods");
if (!Array.isArray(manifest.windowRoles) || !manifest.windowRoles.includes("main-library")) throw new Error("RPC contract must define main-library");
if (!Array.isArray(manifest.implementedWindowRoles) || manifest.implementedWindowRoles.some((role) => role === "main-library" || !manifest.windowRoles.includes(role))) throw new Error("implemented window roles must be known tool roles");
if (new Set(manifest.windowRoles).size !== manifest.windowRoles.length || new Set(manifest.implementedWindowRoles).size !== manifest.implementedWindowRoles.length) throw new Error("window roles must be unique");
const methodNames = new Set<string>();
for (const method of manifest.methods) {
  if (!/^[a-z][a-zA-Z]*(?:\.[a-z][a-zA-Z]*)+$/.test(method.name)) throw new Error(`invalid RPC method: ${method.name}`);
  if (!method.params || !method.result) throw new Error(`RPC method types are required: ${method.name}`);
  if (methodNames.has(method.name)) throw new Error(`duplicate RPC method: ${method.name}`);
  methodNames.add(method.name);
}
const methods = manifest.methods.map((method) => method.name);
await mkdir(new URL("../src/generated/", import.meta.url), { recursive: true });
await Bun.write(new URL("../src/generated/roles.ts", import.meta.url), `// Generated by scripts/generate-contracts.ts. Do not edit.\nexport const windowRoles = ${JSON.stringify(manifest.windowRoles)} as const;\nexport const implementedWindowRoles = ${JSON.stringify(manifest.implementedWindowRoles)} as const;\n`);
await Bun.write(new URL("../src/generated/methods.ts", import.meta.url), `// Generated by scripts/generate-contracts.ts\nexport const rpcMethods = ${JSON.stringify(methods)} as const;\nexport type RpcMethod = typeof rpcMethods[number];\n`);
await Bun.write(new URL("../src/generated/contracts.ts", import.meta.url), `// Generated by scripts/generate-contracts.ts. Do not edit.\nimport type { AboutInfo, Account, AccountManagerModel, AccountNetworkService, AccountUpdate, Bootstrap, CapturedInputButton, CemodApprovalUpdate, CemodManagerResult, ChecksumModel, EmulatedControllerType, EmulatedUsbDeviceId, EmulatedUsbModel, FrontendSettings, FrontendSettingsApplyResult, FrontendSettingsUpdate, GraphicPack, GraphicPackInstallRequest, GraphicPackMutation, HotkeySettingsApplyResult, HotkeySettingsModel, HotkeySettingsUpdate, InputDeviceCandidate, InputSettingsModel, LoggingSnapshot, PhysicalControllerSettings, PpcThreadCommand, PpcThreadCommandResult, PpcThreadsModel, SaveEntryState, SaveIdentity, SaveImportInspection, SaveManagerModel, Title, TitleInstallSelection, TitleManagerModel, UpdateManagerModel, WindowOpenRequest } from "../bridge/contracts";\nexport type EmptyResult = Record<string, never>;\nexport type RpcContract = {\n${manifest.methods.map((method) => `  ${JSON.stringify(method.name)}: { params: ${method.params}; result: ${method.result} };`).join("\n")}\n};\nexport type RpcMethod = keyof RpcContract;\n`);

const cppNames = methods.map((method) => `\t\t"${method}"`).join(",\n");
await mkdir(new URL("../../src/webview/generated/", import.meta.url), { recursive: true });
const cppRoles = manifest.implementedWindowRoles.map((role) => `\t\t"${role}"`).join(",\n");
await Bun.write(new URL("../../src/webview/generated/WindowRoles.h", import.meta.url), `#pragma once\n// Generated by ui/scripts/generate-contracts.ts. Do not edit.\n#include <array>\n#include <string_view>\nnamespace WebFrontend::Generated\n{\n\tinline constexpr std::array<std::string_view, ${manifest.implementedWindowRoles.length}> ImplementedWindowRoles{\n${cppRoles}\n\t};\n}\n`);
await Bun.write(new URL("../../src/webview/generated/RpcMethods.h", import.meta.url), `#pragma once\n// Generated by ui/scripts/generate-contracts.ts. Do not edit.\n#include <array>\n#include <string_view>\nnamespace WebFrontend::Generated\n{\n\tinline constexpr std::array<std::string_view, ${methods.length}> RpcMethods{\n${cppNames}\n\t};\n}\n`);
