import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { TitleManagerEntry, TitleManagerModel } from "../bridge/contracts";
import { subscribe } from "../bridge/events";
import { invoke } from "../bridge/native";
import { activateJob, routeJobEvent } from "./checksumEvents";

type JobEvent = { type: string; payload: Record<string, unknown> };
type Progress = { phase: string; filesCompleted: number; filesTotal: number; bytesCompleted: number; bytesTotal: number };

export function TitleManagerWindow({ windowId }: { windowId: number }) {
  const [model, setModel] = useState<TitleManagerModel>({ scanning: false, entries: [] });
  const [selectedUid, setSelectedUid] = useState(""); const [query, setQuery] = useState(""); const [kind, setKind] = useState("all");
  const [error, setError] = useState(""); const [progress, setProgress] = useState<Progress>(); const [checksumSummary, setChecksumSummary] = useState("");
  const jobId = useRef<number | undefined>(undefined); const pendingEvents = useRef(new Map<number, JobEvent[]>()); const loadSequence = useRef(0);
  const load = useCallback(async () => { const sequence = ++loadSequence.current; try { const next = await invoke("titleManager.getModel"); if (sequence !== loadSequence.current) return; setModel(next); setSelectedUid((current) => next.entries.some((entry) => entry.locationUid === current) ? current : next.entries[0]?.locationUid ?? ""); } catch (reason) { if (sequence === loadSequence.current) setError(String(reason)); } }, []);
  const applyJobEvent = useCallback((event: JobEvent) => { const payload = event.payload; if (event.type === "jobs.progress") { setProgress({ phase: String(payload.phase ?? "working"), filesCompleted: Number(payload.filesCompleted ?? 0), filesTotal: Number(payload.filesTotal ?? 0), bytesCompleted: Number(payload.bytesCompleted ?? 0), bytesTotal: Number(payload.bytesTotal ?? 0) }); return; } jobId.current = undefined; setProgress(undefined); if (payload.ok === true && payload.checksum && typeof payload.checksum === "object") { const result = payload.checksum as { files?: unknown[]; imageSha256?: string }; setChecksumSummary(result.imageSha256 ? `Image SHA-256: ${result.imageSha256}` : `${result.files?.length ?? 0} files verified`); } else setError(String(payload.diagnostic || "Checksum operation failed")); }, []);
  useEffect(() => { void load(); return subscribe((event) => { if (event.type === "titles.changed") { void load(); return; } if ((event.type !== "jobs.progress" && event.type !== "jobs.completed") || !event.payload || typeof event.payload !== "object") return; const payload = event.payload as Record<string, unknown>; if (payload.windowId !== windowId || typeof payload.jobId !== "number") return; routeJobEvent(pendingEvents.current, jobId.current, payload.jobId, { type: event.type, payload }, applyJobEvent); }); }, [applyJobEvent, load, windowId]);
  const entries = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return model.entries.filter((entry) => (kind === "all" || entry.type === kind) && (!needle || `${entry.name} ${entry.titleId} ${entry.path} ${entry.region}`.toLocaleLowerCase().includes(needle))); }, [kind, model.entries, query]);
  const selected = model.entries.find((entry) => entry.locationUid === selectedUid);
  const refresh = async () => { setError(""); try { await invoke("titleManager.refresh"); await load(); } catch (reason) { setError(String(reason)); } };
  const launch = async (entry: TitleManagerEntry) => { setError(""); try { await invoke("titleManager.launch", { locationUid: entry.locationUid }); await invoke("window.close"); } catch (reason) { setError(String(reason)); } };
  const verify = async (entry: TitleManagerEntry) => { setError(""); setChecksumSummary(""); setProgress({ phase: "starting", filesCompleted: 0, filesTotal: 0, bytesCompleted: 0, bytesTotal: 0 }); try { const started = await invoke("checksum.start", { locationUid: entry.locationUid }); jobId.current = started.jobId; activateJob(pendingEvents.current, started.jobId, applyJobEvent); } catch (reason) { setProgress(undefined); setError(String(reason)); } };
  const cancel = () => { if (jobId.current !== undefined) void invoke("jobs.cancel", { jobId: jobId.current }).catch((reason: unknown) => setError(String(reason))); };
  const percent = progress ? progress.bytesTotal ? progress.bytesCompleted * 100 / progress.bytesTotal : progress.filesTotal ? progress.filesCompleted * 100 / progress.filesTotal : 0 : 0;
  return <main className="role-window manager-window"><header><div><span className="eyebrow">Installed content</span><h1>Title Manager</h1></div><div className="button-row"><button disabled={model.scanning || !!progress} onClick={() => void refresh()}>Refresh</button>{progress && <button onClick={cancel}>Cancel</button>}<button onClick={() => void invoke("window.close")}>Close</button></div></header>
    {error && <div className="notice error" role="alert">{error}</div>}<div className="toolbar embedded"><input type="search" placeholder="Filter titles, IDs, or paths" value={query} onChange={(event) => setQuery(event.target.value)} /><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="all">All content</option><option value="base">Base</option><option value="update">Updates</option><option value="dlc">DLC</option><option value="system">System</option></select><span>{entries.length} installations{model.scanning ? " · scanning…" : ""}</span></div>
    <div className="split-view"><aside className="selection-list">{entries.map((entry) => <button key={entry.locationUid} className={entry.locationUid === selectedUid ? "selected" : ""} disabled={!!progress} onClick={() => { setSelectedUid(entry.locationUid); setChecksumSummary(""); }}><strong>{entry.name || entry.titleId}</strong><span>{entry.type} · {entry.format} · v{entry.version}</span><code>{entry.titleId}</code></button>)}</aside><section className="editor-panel">{selected ? <><h2>{selected.name || selected.titleId}</h2><dl className="detail-list compact"><div><dt>Title ID</dt><dd><code>{selected.titleId}</code></dd></div><div><dt>Installed path</dt><dd><code>{selected.path}</code></dd></div><div><dt>Region / version</dt><dd>{selected.region || "Unknown"} · v{selected.version}</dd></div><div><dt>Content</dt><dd>{selected.type} / {selected.format}</dd></div></dl><div className="button-row">{selected.canLaunch && <button disabled={!!progress} onClick={() => void launch(selected)}>Launch title</button>}<button disabled={!selected.canVerify || !!progress} onClick={() => void verify(selected)}>Verify integrity</button></div>{progress && <><progress max={100} value={percent}/><p className="muted">{progress.phase}: {progress.filesCompleted}/{progress.filesTotal} files · {Math.round(progress.bytesCompleted / 1048576)}/{Math.round(progress.bytesTotal / 1048576)} MiB</p></>}{checksumSummary && <div className="notice">{checksumSummary}</div>}</> : <p>No managed content matches the filter.</p>}</section></div></main>;
}
