file(GLOB_RECURSE architecture_sources
	"${SOURCE_ROOT}/src/*.h"
	"${SOURCE_ROOT}/src/*.hpp"
	"${SOURCE_ROOT}/src/*.cpp"
	"${SOURCE_ROOT}/src/CMakeLists.txt")

set(locator_violations "")
set(lower_gui_violations "")
set(cafe_ui_violations "")
set(title_ui_violations "")
set(graphic_pack_ui_violations "")
set(game_list_ui_violations "")
set(title_manager_event_violations "")
set(checksum_ui_violations "")
set(game_profile_ui_violations "")
set(title_install_ui_violations "")
set(wx_wire_violations "")
set(wx_presentation_violations "")
set(wx_vsync_violations "")
set(wx_swkbd_violations "")
set(wx_nfc_violations "")
set(wx_renderer_adapter_violations "")
set(wx_audio_spec_violations "")
set(download_list_title_violations "")
set(debugger_adapter_boundary_violations "")

foreach(source IN LISTS architecture_sources)
	file(READ "${source}" content)
	if(content MATCHES "Frontend::GetHostServices|frontend/HostServices\\.h")
		list(APPEND locator_violations "${source}")
	endif()

	if(source MATCHES "/src/(Cafe|Cemu|input|audio|imgui|config)/")
		if(content MATCHES "gui/interface/WindowSystem\\.h|interface/WindowSystem\\.h|WindowSystem::")
			list(APPEND lower_gui_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/Cafe/" AND content MATCHES "#include[ \t]*[<\"]wx/|#include[ \t]*[<\"]wx")
		list(APPEND cafe_ui_violations "${source}")
	endif()

	# These normal frontend files have moved behind Application::ITitleCatalog.
	# Prevent accidental reintroduction while the larger game-list/title-manager
	# migration proceeds through its own copied DTO/event boundary.
	if(source MATCHES "/src/gui/wxgui/(MainWindow|CemuApp|GeneralSettings2|GettingStartedDialog)\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/TitleList/|CafeTitleList::|CafeSaveList::|TitleInfo|GameInfo2")
			list(APPEND title_ui_violations "${source}")
		endif()
	endif()

	# Graphic-pack windows consume copied Application DTOs and commands only.
	if(source MATCHES "/src/gui/wxgui/(GraphicPacksWindow2|DownloadGraphicPacksWindow|DownloadCustomGraphicPackWindow)\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|GraphicPack2|CafeSystem::|CafeTitleList::|LatteAsyncCommands")
			list(APPEND graphic_pack_ui_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/components/wxGameList\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeTitleList|GameInfo2|TitleInfo|iosu::pdm|fsc_extractFile|FSC_PRIORITY")
			list(APPEND game_list_ui_violations "${source}")
		endif()
	endif()

	# Title-manager discovery/removal/scan events and WUA conversion cross the
	# Application boundary as copied values and content-operation requests.
	if(source MATCHES "/src/gui/wxgui/(TitleManager|components/wxTitleManagerList)\\.h$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeConsoleRegion|CafeTitleListCallbackEvent|CafeSaveListCallbackEvent")
			list(APPEND title_manager_event_violations "${source}")
		endif()
	elseif(source MATCHES "/src/gui/wxgui/TitleManager\\.cpp$")
		if(content MATCHES "CafeTitleList::|CafeSaveList::|CafeTitleListCallbackEvent|CafeSaveListCallbackEvent")
			list(APPEND title_manager_event_violations "${source}")
		endif()
	elseif(source MATCHES "/src/gui/wxgui/components/wxTitleManagerList\\.cpp$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeTitleList|CafeSaveList|TitleInfo|GameInfo2|TitleIdParser|FSC_|fsc_|ZArchive|FileStream|RegisterCallback|UnregisterCallback")
			list(APPEND title_manager_event_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/ChecksumTool\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeTitleList|TitleInfo|GameInfo2|FSC_|fsc_(open|close|read)|wud_(open|close|readData|getWUDSize)|openssl/|EVP_|SHA256[(:]")
			list(APPEND checksum_ui_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/GameProfileWindow\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|Cafe/GameProfile|gameProfileIntegerOption_t|AccurateShaderMulOption|CPUMode::|GraphicAPI")
			list(APPEND game_profile_ui_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/GameUpdateWindow\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|TitleInfo|GameInfo2|TitleIdParser|ActiveSettings|fs::(rename|remove_all|recursive_directory_iterator|copy)")
			list(APPEND title_install_ui_violations "${source}")
		endif()
	endif()

	# Native wx event adapters consume frontend-neutral CEX2 value contracts.
	# Wire declarations and runtime hosts stay behind the Application adapter.
	if(source MATCHES "/src/gui/wxgui/")
		if(content MATCHES "cemuextend/services\\.hpp|cemuextend::wire|Cex2Host")
			list(APPEND wx_wire_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/wxWindowSystem\.cpp$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeSystem::|CafeConsoleRegion|LatteGPUState|g_renderer|RendererAPI")
			list(APPEND wx_presentation_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/MainWindow\.cpp$")
		if(content MATCHES "VsyncDriver|VsyncDriver_notifyWindowPosChanged")
			list(APPEND wx_vsync_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/")
		if(content MATCHES "Cafe/OS/libs/swkbd|swkbd_(hasKeyboardInputHook|keyInput)")
			list(APPEND wx_swkbd_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/")
		if(content MATCHES "Cafe/OS/libs/nfc|nfc::TouchTagFromFile|NFC_TOUCH_TAG_ERROR_")
			list(APPEND wx_nfc_violations "${source}")
		endif()
	endif()

	# Normal wx startup, menu, and hotkey code only sees the neutral renderer
	# adapter. Renderer globals and backend-specific APIs stay in its target.
	if(source MATCHES "/src/gui/wxgui/(CemuApp|MainWindow|GeneralSettings2|input/HotkeySettings)\.cpp$")
		if(content MATCHES "Cafe/HW/Latte/(Core/LatteOverlay|Renderer/)|g_renderer|g_vulkan_available|RendererAPI|MetalRenderer|LatteOverlay_init|InitializeGlobalVulkan")
			list(APPEND wx_renderer_adapter_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/GeneralSettings2\.cpp$")
		if(content MATCHES "Cafe/OS/libs/snd_core/ax\.h|snd_core::AX_|AX_FRAMES_PER_GROUP")
			list(APPEND wx_audio_spec_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/components/wxDownloadManagerList\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/TitleList/|TitleIdParser|GameInfo2|TitleInfo")
			list(APPEND download_list_title_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/windows/PPCThreadsViewer/DebugPPCThreadsWindow\.h$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|OSThread_t|VAddr|unordered_map")
			list(APPEND debugger_adapter_boundary_violations "${source}")
		endif()
	elseif(source MATCHES "/src/gui/wxgui/windows/PPCThreadsViewer/DebugPPCThreadsWindow\.cpp$")
		if(content MATCHES "wxProgressDialogManager|[.]detach[(]")
			list(APPEND debugger_adapter_boundary_violations "${source}")
		endif()
	elseif(source MATCHES "/src/gui/wxgui/debugger/SymbolCtrl\.h$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|MPTR|RPLStoredSymbol")
			list(APPEND debugger_adapter_boundary_violations "${source}")
		endif()
	endif()
endforeach()

if(locator_violations)
	list(JOIN locator_violations "\n  " formatted)
	message(FATAL_ERROR "Global HostServices locator is forbidden:\n  ${formatted}")
endif()
if(lower_gui_violations)
	list(JOIN lower_gui_violations "\n  " formatted)
	message(FATAL_ERROR "Lower-layer WindowSystem dependency is forbidden:\n  ${formatted}")
endif()
if(cafe_ui_violations)
	list(JOIN cafe_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Cafe must not include wx headers:\n  ${formatted}")
endif()
if(title_ui_violations)
	list(JOIN title_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx frontend must use the Application title catalog:\n  ${formatted}")
endif()
if(graphic_pack_ui_violations)
	list(JOIN graphic_pack_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx frontend must use the Application graphic-pack facade:\n  ${formatted}")
endif()
if(game_list_ui_violations)
	list(JOIN game_list_ui_violations "\n  " formatted)
	message(FATAL_ERROR "wxGameList must use copied Application title catalog DTOs:\n  ${formatted}")
endif()
if(title_manager_event_violations)
	list(JOIN title_manager_event_violations "\n  " formatted)
	message(FATAL_ERROR "Title-manager catalog events must use copied Application DTOs:\n  ${formatted}")
endif()
if(checksum_ui_violations)
	list(JOIN checksum_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Checksum UI must use Application content operations:\n  ${formatted}")
endif()
if(game_profile_ui_violations)
	list(JOIN game_profile_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Game-profile UI must use Application profile DTOs:\n  ${formatted}")
endif()
if(title_install_ui_violations)
	list(JOIN title_install_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Title-install UI must use the Application install facade:\n  ${formatted}")
endif()
if(wx_wire_violations)
	list(JOIN wx_wire_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx frontend must not depend on CEX2 wire/runtime types:\n  ${formatted}")
endif()
if(wx_presentation_violations)
	list(JOIN wx_presentation_violations "\n  " formatted)
	message(FATAL_ERROR "wx window presentation must use copied Application DTOs:\n  ${formatted}")
endif()
if(wx_vsync_violations)
	list(JOIN wx_vsync_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx window code must use the renderer window adapter:\n  ${formatted}")
endif()
if(wx_swkbd_violations)
	list(JOIN wx_swkbd_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx input code must use the Application software keyboard API:\n  ${formatted}")
endif()
if(wx_nfc_violations)
	list(JOIN wx_nfc_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx code must use the Application NFC API:\n  ${formatted}")
endif()
if(wx_renderer_adapter_violations)
	list(JOIN wx_renderer_adapter_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx code must use the renderer adapter boundary:\n  ${formatted}")
endif()
if(wx_audio_spec_violations)
	list(JOIN wx_audio_spec_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx audio settings must use the CemuAudio buffer specification:\n  ${formatted}")
endif()
if(download_list_title_violations)
	list(JOIN download_list_title_violations "\n  " formatted)
	message(FATAL_ERROR "wxDownloadManagerList must use its copied title entry classification:\n  ${formatted}")
endif()
if(debugger_adapter_boundary_violations)
	list(JOIN debugger_adapter_boundary_violations "\n  " formatted)
	message(FATAL_ERROR "Debugger adapters must keep core types and detached workers out of their public boundaries:\n  ${formatted}")
endif()
