file(GLOB_RECURSE architecture_sources
	"${SOURCE_ROOT}/src/*.h"
	"${SOURCE_ROOT}/src/*.hpp"
	"${SOURCE_ROOT}/src/*.cpp"
	"${SOURCE_ROOT}/src/CMakeLists.txt")

set(locator_violations "")
set(lower_gui_violations "")
set(cafe_ui_violations "")
set(title_ui_violations "")
set(graphic_pack_ui_violations "")
set(game_list_ui_violations "")
set(title_manager_event_violations "")
set(checksum_ui_violations "")

foreach(source IN LISTS architecture_sources)
	file(READ "${source}" content)
	if(content MATCHES "Frontend::GetHostServices|frontend/HostServices\\.h")
		list(APPEND locator_violations "${source}")
	endif()

	if(source MATCHES "/src/(Cafe|Cemu|input|audio|imgui|config)/")
		if(content MATCHES "gui/interface/WindowSystem\\.h|interface/WindowSystem\\.h|WindowSystem::")
			list(APPEND lower_gui_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/Cafe/" AND content MATCHES "#include[ \t]*[<\"]wx/|#include[ \t]*[<\"]wx")
		list(APPEND cafe_ui_violations "${source}")
	endif()

	# These normal frontend files have moved behind Application::ITitleCatalog.
	# Prevent accidental reintroduction while the larger game-list/title-manager
	# migration proceeds through its own copied DTO/event boundary.
	if(source MATCHES "/src/gui/wxgui/(MainWindow|CemuApp|GeneralSettings2|GettingStartedDialog)\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/TitleList/|CafeTitleList::|CafeSaveList::|TitleInfo|GameInfo2")
			list(APPEND title_ui_violations "${source}")
		endif()
	endif()

	# Graphic-pack windows consume copied Application DTOs and commands only.
	if(source MATCHES "/src/gui/wxgui/(GraphicPacksWindow2|DownloadGraphicPacksWindow|DownloadCustomGraphicPackWindow)\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|GraphicPack2|CafeSystem::|CafeTitleList::|LatteAsyncCommands")
			list(APPEND graphic_pack_ui_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/components/wxGameList\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeTitleList|GameInfo2|TitleInfo|iosu::pdm|fsc_extractFile|FSC_PRIORITY")
			list(APPEND game_list_ui_violations "${source}")
		endif()
	endif()

	# Title-manager discovery/removal/scan events and WUA conversion cross the
	# Application boundary as copied values and content-operation requests.
	if(source MATCHES "/src/gui/wxgui/(TitleManager|components/wxTitleManagerList)\\.h$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeConsoleRegion|CafeTitleListCallbackEvent|CafeSaveListCallbackEvent")
			list(APPEND title_manager_event_violations "${source}")
		endif()
	elseif(source MATCHES "/src/gui/wxgui/TitleManager\\.cpp$")
		if(content MATCHES "CafeTitleList::|CafeSaveList::|CafeTitleListCallbackEvent|CafeSaveListCallbackEvent")
			list(APPEND title_manager_event_violations "${source}")
		endif()
	elseif(source MATCHES "/src/gui/wxgui/components/wxTitleManagerList\\.cpp$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeTitleList|CafeSaveList|TitleInfo|GameInfo2|TitleIdParser|FSC_|fsc_|ZArchive|FileStream|RegisterCallback|UnregisterCallback")
			list(APPEND title_manager_event_violations "${source}")
		endif()
	endif()

	if(source MATCHES "/src/gui/wxgui/ChecksumTool\\.(h|cpp)$")
		if(content MATCHES "#include[ \t]*[<\"]Cafe/|CafeTitleList|TitleInfo|GameInfo2|FSC_|fsc_(open|close|read)|wud_(open|close|readData|getWUDSize)|openssl/|EVP_|SHA256[(:]")
			list(APPEND checksum_ui_violations "${source}")
		endif()
	endif()
endforeach()

if(locator_violations)
	list(JOIN locator_violations "\n  " formatted)
	message(FATAL_ERROR "Global HostServices locator is forbidden:\n  ${formatted}")
endif()
if(lower_gui_violations)
	list(JOIN lower_gui_violations "\n  " formatted)
	message(FATAL_ERROR "Lower-layer WindowSystem dependency is forbidden:\n  ${formatted}")
endif()
if(cafe_ui_violations)
	list(JOIN cafe_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Cafe must not include wx headers:\n  ${formatted}")
endif()
if(title_ui_violations)
	list(JOIN title_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx frontend must use the Application title catalog:\n  ${formatted}")
endif()
if(graphic_pack_ui_violations)
	list(JOIN graphic_pack_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Normal wx frontend must use the Application graphic-pack facade:\n  ${formatted}")
endif()
if(game_list_ui_violations)
	list(JOIN game_list_ui_violations "\n  " formatted)
	message(FATAL_ERROR "wxGameList must use copied Application title catalog DTOs:\n  ${formatted}")
endif()
if(title_manager_event_violations)
	list(JOIN title_manager_event_violations "\n  " formatted)
	message(FATAL_ERROR "Title-manager catalog events must use copied Application DTOs:\n  ${formatted}")
endif()
if(checksum_ui_violations)
	list(JOIN checksum_ui_violations "\n  " formatted)
	message(FATAL_ERROR "Checksum UI must use Application content operations:\n  ${formatted}")
endif()
