function(cemu_collect_target_link_closure root_target out_var)
	set(queue "${root_target}")
	set(visited "")
	set(closure "")
	while(queue)
		list(POP_FRONT queue current)
		if(current IN_LIST visited OR NOT TARGET "${current}")
			continue()
		endif()
		list(APPEND visited "${current}")
		foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
			get_target_property(edges "${current}" "${property}")
			if(NOT edges)
				continue()
			endif()
			foreach(edge IN LISTS edges)
				# Link interfaces commonly wrap private archive edges in
				# $<LINK_ONLY:Target>. Extract every target-shaped token so
				# conditional and TARGET_NAME_IF_EXISTS edges are traversed too.
				string(REGEX MATCHALL
					"[A-Za-z0-9_.+-]+(::[A-Za-z0-9_.+-]+)*"
					edge_candidates "${edge}")
				foreach(candidate IN LISTS edge_candidates)
					if(TARGET "${candidate}")
						list(APPEND closure "${candidate}")
						list(APPEND queue "${candidate}")
					endif()
				endforeach()
			endforeach()
		endforeach()
	endwhile()
	list(REMOVE_DUPLICATES closure)
	set(${out_var} "${closure}" PARENT_SCOPE)
endfunction()

function(cemu_assert_target_closure_has_no_source_path target forbidden_path)
	string(REGEX REPLACE "^/" "" forbidden_relative "${forbidden_path}")
	set(targets "${target}")
	cemu_collect_target_link_closure("${target}" closure)
	list(APPEND targets ${closure})
	foreach(candidate IN LISTS targets)
		if(NOT TARGET "${candidate}")
			continue()
		endif()
		get_target_property(candidate_source_dir "${candidate}" SOURCE_DIR)
		foreach(property SOURCES INTERFACE_SOURCES)
			get_target_property(candidate_sources "${candidate}" "${property}")
			if(NOT candidate_sources)
				continue()
			endif()
			foreach(source IN LISTS candidate_sources)
				string(REPLACE "\\" "/" normalized_expression "${source}")
				string(FIND "${normalized_expression}" "${forbidden_relative}" forbidden_expression_position)
				if(NOT forbidden_expression_position EQUAL -1)
					message(FATAL_ERROR
						"Retired frontend source reached ${target} through ${candidate}: ${source}")
				endif()
				if(source MATCHES "^\\$<")
					continue()
				endif()
				if(IS_ABSOLUTE "${source}")
					set(source_path "${source}")
				else()
					set(source_path "${candidate_source_dir}/${source}")
				endif()
				get_filename_component(source_path "${source_path}" ABSOLUTE)
				file(TO_CMAKE_PATH "${source_path}" normalized_source)
				if(normalized_source MATCHES "${forbidden_path}")
					message(FATAL_ERROR
						"Retired frontend source reached ${target} through ${candidate}: ${normalized_source}")
				endif()
			endforeach()
		endforeach()
	endforeach()
endfunction()
