function(cemu_assert_target_internal_edges_allowed target)
	if(NOT TARGET "${target}")
		return()
	endif()
	set(direct_edges "")
	foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
		get_target_property(property_edges "${target}" "${property}")
		if(property_edges)
			list(APPEND direct_edges ${property_edges})
		endif()
	endforeach()
	foreach(edge IN LISTS direct_edges)
		if(TARGET "${edge}" AND edge MATCHES "^Cemu" AND NOT edge IN_LIST ARGN)
			message(FATAL_ERROR
				"Architecture allow-matrix violation: ${target} -> ${edge}")
		endif()
	endforeach()
endfunction()
